from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any

import chainlit as cl
import httpx


DEFAULT_BACKEND_URL = "http://localhost:6100"


@dataclass(slots=True)
class BackendChatResponse:
    session_id: str | None
    answer: str
    citations: list[dict[str, Any]] = field(default_factory=list)


class BackendChatClient:
    def __init__(
        self,
        base_url: str | None = None,
        auth_token: str | None = None,
        timeout_seconds: float | None = None,
    ) -> None:
        self.base_url = (base_url or os.getenv("BACKEND_URL") or DEFAULT_BACKEND_URL).rstrip("/")
        self.auth_token = auth_token if auth_token is not None else os.getenv("CHAINLIT_BACKEND_AUTH_TOKEN")
        self.timeout_seconds = timeout_seconds or float(os.getenv("CHAINLIT_BACKEND_TIMEOUT_SECONDS", "30"))

    async def ask(self, message: str, session_id: str | None) -> BackendChatResponse:
        payload: dict[str, str] = {"message": message}
        if session_id:
            payload["session_id"] = session_id

        headers = {"Accept": "application/json"}
        if self.auth_token:
            headers["Authorization"] = f"Bearer {self.auth_token}"

        async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
            response = await client.post(f"{self.base_url}/api/v1/chat", json=payload, headers=headers)

        if response.status_code == 202:
            data = response.json()
            return BackendChatResponse(
                session_id=data.get("session_id") if isinstance(data, dict) else session_id,
                answer="The previous request is still processing. Please retry in a moment.",
                citations=[],
            )

        response.raise_for_status()
        data = response.json()
        return BackendChatResponse(
            session_id=str(data["session_id"]),
            answer=str(data["answer"]),
            citations=list(data.get("citations") or []),
        )


def render_answer_with_citations(answer: str, citations: list[dict[str, Any]]) -> str:
    if not citations:
        return answer
    markers = "".join(_superscript(int(citation["number"])) for citation in citations if citation.get("number"))
    notes = "\n".join(_render_note(citation) for citation in citations)
    return f"{answer.rstrip()}{markers}\n\n{notes}"


def _render_note(citation: dict[str, Any]) -> str:
    number = int(citation["number"])
    title = str(citation.get("document_title") or "Uploaded document")
    page = citation.get("page_number")
    section = citation.get("section_path")
    location = f", p. {page}" if page is not None else ""
    section_text = f", {section}" if section else ""
    return f"{number}. {title}{location}{section_text}."


def _superscript(value: int) -> str:
    digits = str(value).translate(str.maketrans("0123456789", "⁰¹²³⁴⁵⁶⁷⁸⁹"))
    return digits


def _chat_client() -> BackendChatClient:
    configured = cl.user_session.get("backend_chat_client")
    if configured is not None:
        return configured
    client = BackendChatClient()
    cl.user_session.set("backend_chat_client", client)
    return client


@cl.on_chat_start
async def start_chat() -> None:
    cl.user_session.set("backend_session_id", None)
    await cl.Message(
        content=(
            "# Document-grounded RAG chat\n\n"
            "Upload and index PDFs in the document manager, then ask a question here. "
            "Responses are generated by the FastAPI RAG pipeline and include source notes when retrieved chunks support the answer."
        )
    ).send()


@cl.on_message
async def handle_message(message: cl.Message) -> None:
    user_input = message.content.strip()
    if not user_input:
        await cl.Message(content="Please enter a question.").send()
        return

    try:
        response = await _chat_client().ask(
            user_input,
            session_id=cl.user_session.get("backend_session_id"),
        )
    except httpx.HTTPStatusError as exc:
        await cl.Message(content=f"Backend rejected the request with status {exc.response.status_code}.").send()
        return
    except httpx.HTTPError:
        await cl.Message(content="Backend chat is unavailable. Check that FastAPI is running on port 6100.").send()
        return

    if response.session_id:
        cl.user_session.set("backend_session_id", response.session_id)
    await cl.Message(content=render_answer_with_citations(response.answer, response.citations)).send()
